name: Update Version on Release

on:
  release:
    types: [published]

jobs:
  update-version:
    runs-on: ubuntu-latest
    env:
      PYPI_PACKAGE_NAME: 'tcrdiscord'  # package name for easy adjustment

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Update version.py
      run: |
        # Extract release title
        VERSION="${{ github.event.release.name }}"
        PACKAGE_NAME="${{ env.PYPI_PACKAGE_NAME }}"
        echo "Updating ${PACKAGE_NAME}/version.py to version ${VERSION}"

        # Update the __version__ in ${PACKAGE_NAME}/version.py
        sed -i "s/__version__ = .*/__version__ = '${VERSION}'/" "${PACKAGE_NAME}/version.py"

    - name: Commit and push changes
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add "${PACKAGE_NAME}/version.py"
        git commit -m "Update ${PACKAGE_NAME}/version.py to ${VERSION}"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
